---
driver:
  name: ec2
  region: eu-west-2
  instance_type: t2.medium
  require_chef_omnibus: 13.8.5

transport:
  name: sftp
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY_ID'] %>

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-16.04

verifier:
  name: busser
  version: 0.6.0

common: &common
  roles_path: roles
  encrypted_data_bag_secret_key_path: 'encrypted_data_bag_secret'

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    data_bags_path: "test/integration/mysql/data_bags"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: sqlite
        ssl_data_bag_name: redmine_example_com
    <<: *common
  - name: mysql
    data_bags_path: "test/integration/mysql/data_bags"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: mysql
        ssl_data_bag_name: redmine_example_com
      mysql:
        server_root_password: q654321
        server_repl_password: q654321
        server_debian_password: q654321
    <<: *common
  - name: postgresql
    data_bags_path: "test/integration/postgresql/data_bags"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[postgresql::server]
      - recipe[redmine2]
      - recipe[redmine2::plugins]
      - recipe[redmine2::iptables]
    attributes:
      apt:
        compile_time_update: true
        repository_uri: "http://uk.archive.ubuntu.com/ubuntu/"
      redmine:
        host: redmine.dev
        db:
          type: postgresql
        ssl_data_bag_name: redmine_example_com
      postgresql:
        password:
          postgres: q654321
          redmine: redmine
      openssh:
        server:
          permit_root_login: "yes"
      build_essential:
        compiletime: true
    <<: *common